services:
  - type: web
    name: todo-list
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn project01.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"  # Set this to the actual database URL format Render supports.

databases:
  - name: sqlite
    plan: free
